language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
cache:
  directories:
    - node_modules
before_script:
  - npm i
script:
  - npm run test
# after_script:
#   - npm run coverage
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master